document.writeln("<style type=\"text\/css\">");
document.writeln("<!--");
document.writeln(".style11 {color: #FF0000; font-size: 14px; }");
document.writeln(".style13 {color: #00007B; font-size: 14px; }");
document.writeln(".STYLE6 {font-size: 12px}");
document.writeln(".STYLE8 {font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-weight: bold; }");
document.writeln(".STYLE9 {border:1px solid #96BDDE }");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("<table width=\"900\" border=\"0\" cellspacing=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td><table class=\"STYLE9\" width=\"900\" height=\"100\" border=\"0\" cellspacing=\"0\" bordercolor=\"#FFFFFF\">");
document.writeln("      <tr>");
document.writeln("        <td><table width=\"100%\" height=\"100\" border=\"0\" cellspacing=\"0\">");
document.writeln("              <tr>");
document.writeln("                <td><div style=\"font-size:10px \">");
document.writeln("                    <table width=\"100%\" height=\"100\" border=\"0\" cellPadding=\"0\" cellSpacing=\"0\" align=\"center\"  bgcolor=\"#FBF9CC\">");
document.writeln("                      <tr>");
document.writeln("                        <TD valign=\"middle\" ><div align=\"center\" class=\"STYLE8\"><a href=\"http:\/\/www.eetchina.com\/ART_8800459232_617687_TA_9dac756c.HTM?click_from=et_dz\" target=\"_blank\"><font color=red>电子工程师必备手册<\/font><\/a><\/div><\/td>");
document.writeln("                      <\/tr>");
document.writeln("                      <tr>");
document.writeln("                        <td valign=\"middle\"><div align=\"center\">");
document.writeln("                            <div align=\"center\" class=\"STYLE8\"><a href=\"http:\/\/www.eetchina.com\/ART_8800487824_628868_TA_c1938b8d.HTM?click_from=et_dz\" target=\"_blank\"><font color=#0000CC>LED技术全攻略<\/font><\/a><\/div>");
document.writeln("                        <\/div><\/td>");
document.writeln("                      <\/tr>");
document.writeln("                      <tr>");
document.writeln("                        <TD valign=\"middle\" ><div align=\"center\" class=\"STYLE8\"><a href=\"http:\/\/www.eetchina.com\/ART_8800469132_480601_TA_ba1345b9.HTM?click_from=et_dz\" target=\"_blank\"><font color=red>EMI\/EMC设计秘籍<\/font><\/a><span class=\"STYLE6\"><FONT COLOR=RED>(PDF)<\/FONT><\/span><\/div><\/td>");
document.writeln("                      <\/tr>");
document.writeln("                      <tr>");
document.writeln("                        <td valign=\"middle\" ><div align=\"center\" class=\"STYLE8\"><a href=\"http:\/\/www.eetchina.com\/ART_8800468660_621496_TA_0f8db934.HTM?click_from=et_dz\" target=\"_blank\"><font color=#0000CC>硬件工程师必读攻略<\/font><\/a><span class=\"STYLE6\"><font color=\"RED\">(PDF)<\/font><\/span><\/div><\/td>");
document.writeln("                      <\/tr>");
document.writeln("                    <\/table>");
document.writeln("                <\/div><\/td>");
document.writeln("              <\/tr>");
document.writeln("        <\/table><\/td>");
document.writeln("        <\/tr>");
document.writeln("    <\/table><\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td><table width=\"100%\" height=\"1\"  border=\"0\" cellspacing=\"0\">");
document.writeln("      <tr>");
document.writeln("        <td><\/td>");
document.writeln("      <\/tr>");
document.writeln("    <\/table><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("")