(function(){
var g=false,i=null,m=true,aa=(new Date).getTime();var ba={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type",google_page_url:"url"},ca={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_analytics_uacct:"ga_wpids",
google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"};function da(){}da.prototype.Fb=function(){};da.prototype.Gb=function(){};da.prototype.Eb=function(){};var o=i;function ea(a){o&&o.Fb(a)}function fa(a){o&&o.Gb(a)}function ga(a){o&&o.Eb(a)}function r(){this.H=this.ub();this.na=g;if(!this.H){this.na=this.Za();this.na||fa("Browser does not allow cookies")}}r.prototype.ea="__gads=";r.prototype.Q="GoogleAdServingTest=";r.prototype.gb=function(){return this.H};
r.prototype.setCookieInfo=function(a){this.B=a._cookies_[0];if(this.B!=i){this.H=this.B._value_;this.Db()}};r.prototype.bb=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
r.prototype.ab=function(a){if(this.H!=i||!this.na){ea("Skipping fetch cookie call");return}var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+ha(a)+"&domain="+ha(c);ea("Issuing a fetch cookie call with <a href='"+d+"'>"+d+"</a>");document.write("<"+b+' src="'+d+'"></'+b+">")};
r.prototype.Za=function(){document.cookie=this.Q+"Good";var a=this.Aa(this.Q),b=a=="Good";if(b){var c=this.bb(-1);document.cookie=this.Q+"; expires="+c.toGMTString()}return b};r.prototype.ub=function(){var a=this.Aa(this.ea);a!=i?ea("Read first party cookie: "+a):fa("No first party cookie found");return a};r.prototype.Aa=function(a){var b=document.cookie,c=b.indexOf(a),d=i;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};
r.prototype.Db=function(){if(this.B==i)fa("Skipping cookie creation: no cookie info");else if(this.H==i)ga("Skipping cookie creation: no cookie value");else{var a=new Date;a.setTime(1000*this.B._expires_);var b=this.B._domain_,c=this.ea+this.H+"; expires="+a.toGMTString()+"; path="+this.B._path_+"; domain=."+b;document.cookie=c;ea("Written cookie: "+c)}};function ia(a,b){var c;return a?(c=parseFloat(a))?c:b:b}
function ja(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;while(c)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=i}return b.toString()}else if(ka()){var c=i;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=i){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var la=la||{},s=this;var na=function(a,b,c){var d=a.split("."),e=c||s,f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);while(d.length&&(f=d.shift()))if(!d.length&&ma(b))e[f]=b;else e=e[f]?e[f]:(e[f]={})},oa=function(a,b){var c=a.split("."),d=b||s;for(var e;e=c.shift();)if(d[e])d=d[e];else return i;return d};
var t=function(a){var b=typeof a;if(b=="object")if(a){if(typeof a.length=="number"&&typeof a.splice!="undefined"&&!pa(a,"length"))return"array";if(typeof a.call!="undefined")return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},qa=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return m;return g};
if(Object.prototype.propertyIsEnumerable)var pa=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):qa(a,b)};else pa=qa;var ma=function(a){return typeof a!="undefined"};var ra=function(a){var b=t(a);return b=="array"||b=="object"&&typeof a.length=="number"};
var u=function(a){return t(a)=="function"},sa=function(a){var b=t(a);return b=="object"||b=="array"||b=="function"},va=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(ta)){var b=a[ta];if(b)return b}a[ta]||(a[ta]=++ua);return a[ta]},ta="closure_hashCode_",ua=0,v=function(a,b){var c=a.Hb;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,c);c=d}b=a.Jb||b;a=a.Ib||a;var e,f=b||s;e=c?function(){var h=Array.prototype.slice.call(arguments);h.unshift.apply(h,c);return a.apply(f,
h)}:function(){return a.apply(f,arguments)};e.Hb=c;e.Jb=b;e.Ib=a;return e},wa=Date.now||function(){return(new Date).getTime()},xa=function(a,b,c){na(a,b,c)},x=function(a,b){function c(){}c.prototype=b.prototype;a.n=b.prototype;a.prototype=new c;a.prototype.constructor=a};var ya=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);var d=c==i?0:c<0?Math.max(0,a.length+c):c;for(var e=d;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},za=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else{var d=a.length,e=typeof a=="string"?a.split(""):a;for(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)}},Aa=function(a,b){var c=ya(a,b),d;if(d=c!=-1)Array.prototype.splice.call(a,c,1).length==1;return d};
var Ba=function(a){if(t(a)=="array")return a.concat();else{var b=[];for(var c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var Ca=function(a,b){this.x=ma(a)?a:0;this.y=ma(b)?b:0};Ca.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var y=function(a,b){this.width=a;this.height=b};y.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};y.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};y.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};y.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
y.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Da=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var Ea=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ka=function(a,b){if(b)return a.replace(Fa,"&amp;").replace(Ga,"&lt;").replace(Ha,"&gt;").replace(Ia,"&quot;");else{if(!Ja.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Fa,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(Ga,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Ha,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Ia,"&quot;");return a}},Fa=/&/g,Ga=/</g,Ha=/>/g,Ia=/\"/g,Ja=/[&<>\"]/,La=function(a,b){var c=b.length;for(var d=0;d<c;d++){var e=
c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},Na=function(a,b){var c=0,d=Ea(String(a)).split("."),e=Ea(String(b)).split("."),f=Math.max(d.length,e.length);for(var h=0;c==0&&h<f;h++){var j=d[h]||"",k=e[h]||"",l=new RegExp("(\\d*)(\\D*)","g"),n=new RegExp("(\\d*)(\\D*)","g");do{var p=l.exec(j)||["","",""],q=n.exec(k)||["","",""];if(p[0].length==0&&q[0].length==0)break;var w=p[1].length==0?0:parseInt(p[1],10),L=q[1].length==0?0:parseInt(q[1],
10);c=Ma(w,L)||Ma(p[2].length==0,q[2].length==0)||Ma(p[2],q[2])}while(c==0)}return c},Ma=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za=function(){if(s.navigator)return s.navigator.userAgent;return i},$a=function(){var a=g,b=g,c=g,d=g,e=g,f=g,h=g,j=g,k=g,l="",n=Za();if(n){var p=s.navigator;a=n.indexOf("Opera")==0;b=!a&&n.indexOf("MSIE")!=-1;c=!a&&n.indexOf("WebKit")!=-1;k=c&&n.indexOf("Mobile")!=-1;d=!a&&!c&&p.product=="Gecko";e=d&&p.vendor=="Camino";var q,w;if(s.opera&&typeof s.opera.version=="function")q=s.opera.version();else{if(d)w=/rv\:([^\);]+)(\)|;)/;else if(b)w=/MSIE\s+([^\);]+)(\)|;)/;
else if(c)w=/WebKit\/(\S+)/;if(w){w.test(n);q=RegExp.$1}}l=p.platform||"";f=l.indexOf("Mac")!=-1;h=l.indexOf("Win")!=-1;j=l.indexOf("Linux")!=-1}Oa=a;Pa=b;Qa=d;Ra=e;Sa=c;Ta=k;Ua=q;Va=l;Wa=f;Xa=h;Ya=j};$a();var ab=Oa,z=Pa,fb=Qa,A=Sa,gb=Ta;var B=function(a){return Na(Ua,a)>=0};var hb;var ib=function(){hb||(hb=new C);return hb},kb=function(a){return a?new C(jb(a)):ib()};
var lb=function(a){return typeof a=="string"?document.getElementById(a):a},mb=lb,ob=function(a,b){Da(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in nb)a.setAttribute(nb[d],c);else a[d]=c})},nb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder"},pb=function(a){var b=a||s||window,c=b.document;if(A&&!B("500")&&
!gb){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new y(b.innerWidth,d)}var f=kb(c),h=f.db()=="CSS1Compat"&&(!ab||ab&&B("9.50"))?c.documentElement:c.body;return new y(h.clientWidth,h.clientHeight)};var qb=function(a,b){a.appendChild(b)},rb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):i};
var sb=A&&Na(Ua,"521")<=0,tb=function(a,b){if(typeof a.contains!="undefined"&&!sb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);while(b&&a!=b)b=b.parentNode;return b==a},jb=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},ub=function(a){if(a&&typeof a.length=="number")if(sa(a))return typeof a.item=="function"||typeof a.item=="string";else if(u(a))return typeof a.item=="function";return g},
C=function(a){this.p=a||s.document||document};C.prototype.eb=function(){return this.p};C.prototype.Ra=function(a,b){if(z&&b&&b.name)a="<"+a+' name="'+Ka(b.name)+'">';var c=this.createElement(a);b&&ob(c,b);if(arguments.length>2){function d(h){if(h)this.appendChild(c,typeof h=="string"?this.createTextNode(h):h)}for(var e=2;e<arguments.length;e++){var f=arguments[e];ra(f)&&!(sa(f)&&f.nodeType>0)?za(ub(f)?Ba(f):f,d,this):d.call(this,f)}}return c};C.prototype.createElement=function(a){return this.p.createElement(a)};
C.prototype.createTextNode=function(a){return this.p.createTextNode(a)};C.prototype.db=function(){if(this.p.compatMode)return this.p.compatMode;if(A){var a=this.Ra("div",{style:"position:absolute;width:0;height:0;width:1"}),b=a.style.width=="1px"?"BackCompat":"CSS1Compat";return this.p.compatMode=b}return"BackCompat"};
C.prototype.ta=function(){var a=this.p,b,c;if(!A&&a.compatMode=="CSS1Compat"){b=a.documentElement.scrollLeft;c=a.documentElement.scrollTop}else{b=a.body.scrollLeft;c=a.body.scrollTop}return new Ca(b,c)};C.prototype.appendChild=qb;C.prototype.removeNode=rb;C.prototype.contains=tb;var vb,wb=function(a,b){var c=jb(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return i};
var xb=function(a){return wb(a,"position")||(a.currentStyle?a.currentStyle.position:i)||a.style.position},yb=function(a){var b;b=a?a.nodeType==9?a:jb(a):ib().eb();if(z&&b.compatMode!="CSS1Compat")return b.body;return b.documentElement},zb=function(a){var b=jb(a),c=fb&&b.getBoxObjectFor&&xb(a)=="absolute"&&(a.style.top==""||a.style.left=="");if(typeof vb=="undefined")vb=Ra&&!B("1.8.0.11");var d=new Ca(0,0),e=yb(b);if(a==e)return d;var f=i,h;if(a.getBoundingClientRect&&!c){h=a.getBoundingClientRect();
var j=kb(b).ta();d.x=h.left+j.x;d.y=h.top+j.y}else if(b.getBoxObjectFor&&!c&&!vb){h=b.getBoxObjectFor(a);var k=b.getBoxObjectFor(e);d.x=h.screenX-k.screenX;d.y=h.screenY-k.screenY}else{f=a;do{d.x+=f.offsetLeft;d.y+=f.offsetTop;if(f!=a){d.x+=f.clientLeft||0;d.y+=f.clientTop||0}if(A&&xb(f)=="fixed"){d.x+=b.body.scrollLeft;d.y+=b.body.scrollTop;break}f=f.offsetParent}while(f&&f!=a);if(ab||A&&xb(a)=="absolute")d.y-=b.body.offsetTop;f=a.offsetParent;while(f&&f!=b.body){d.x-=f.scrollLeft;if(!ab||f.tagName!=
"TR")d.y-=f.scrollTop;f=f.offsetParent}}if(fb&&a.getBoundingClientRect){var l=xb(a);if(l=="static"||l=="relative"){d.x=Math.floor(d.x);d.y=Math.floor(d.y)}}return d},Ab=function(a){var b=new Ca;if(a.nodeType==1)if(a.getBoundingClientRect){var c=a.getBoundingClientRect();b.x=c.left;b.y=c.top}else{var d=kb(a).ta(),e=zb(a);b.x=e.x-d.x;b.y=e.y-d.y}else{b.x=a.clientX;b.y=a.clientY}return b},Bb=function(a){var b=jb(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=
wb(a,"fontFamily")||(a.currentStyle?a.currentStyle.fontFamily:i)||a.style.fontFamily;if(ab&&Ya)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return La(c,"\"'")};var Cb=document,D=navigator,E=window;
function Db(){var a=Cb.cookie,b=Math.round((new Date).getTime()/1000),c=E.google_analytics_domain_name,d=typeof c=="undefined"?Eb("auto"):Eb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,h=a.indexOf("__utmc="+d)>-1,j,k={};if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&h?j[3]+"":E&&E.gaGlobal&&E.gaGlobal.sid?E.gaGlobal.sid:b+"";k.vid=j[0]+"."+j[1];k.from_cookie=m}else{k.sid=E&&E.gaGlobal&&E.gaGlobal.sid?E.gaGlobal.sid:b+"";k.vid=E&&E.gaGlobal&&E.gaGlobal.vid?
E.gaGlobal.vid:(Fb()^Gb()&2147483647)+"."+b;k.from_cookie=g}k.dh=d;k.hid=E&&E.gaGlobal&&E.gaGlobal.hid?E.gaGlobal.hid:Fb();E.gaGlobal=k;return k}function Fb(){return Math.round(Math.random()*2147483647)}
function Gb(){var a=Cb.cookie?Cb.cookie:"",b=E.history.length,c,d,e=[D.appName,D.version,D.language?D.language:D.browserLanguage,D.platform,D.userAgent,D.javaEnabled()?1:0].join("");if(E.screen)e+=E.screen.width+"x"+E.screen.height+E.screen.colorDepth;else if(E.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=Cb.referrer?Cb.referrer:"";c=e.length;while(b>0)e+=b--^c++;return Hb(e)}
function Hb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Eb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Cb.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Hb(a.toLowerCase())};var F=function(){};F.prototype.sa=g;F.prototype.dispose=function(){if(!this.sa){this.b();this.sa=m}};F.prototype.b=function(){};var Ib=function(a){if(/^\s*$/.test(a))return g;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x1f\x7f-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},Jb=function(a){String(a);if(Ib(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Kb=i,Lb=function(a){Kb||(Kb=new G);return Kb.serialize(a)},G=function(){};
G.prototype.serialize=function(a){var b=[];this.ca(a,b);return b.join("")};G.prototype.ca=function(a,b){switch(typeof a){case "string":this.Da(a,b);break;case "number":this.Ab(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==i){b.push("null");break}if(t(a)=="array"){this.zb(a,b);break}this.Bb(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var Mb={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"};G.prototype.Da=function(a,b){b.push('"',a.replace(/[\\\"\x00-\x1f\x80-\uffff]/g,function(c){if(c in Mb)return Mb[c];var d=c.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return Mb[c]=e+d.toString(16)}),'"')};G.prototype.Ab=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};
G.prototype.zb=function(a,b){var c=a.length;b.push("[");var d="";for(var e=0;e<c;e++){b.push(d);this.ca(a[e],b);d=","}b.push("]")};G.prototype.Bb=function(a,b){b.push("{");var c="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b.push(c);this.Da(d,b);b.push(":");this.ca(e,b);c=","}}b.push("}")};var H="SETUP_ACK",I={},Ob=function(a,b){var c=b||Nb,d=c.length,e="";while(a-- >0)e+=c.charAt(Math.floor(Math.random()*d));return e},Nb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var Pb=function(){};x(Pb,F);var J=function(a){this.a=a;this.O=[];this.Ob=v(this.Xa,this)};x(J,Pb);J.prototype.Z=g;J.prototype.Cb=0;J.prototype.connect=function(){if(this.a.r()==0){this.k=this.a.s;this.k.XPC_toOuter=v(this.ua,this)}else this.ia()};
J.prototype.ia=function(){var a=m;try{if(!this.k)this.k=window.frameElement;if(this.k&&this.k.XPC_toOuter){this.ya=this.k.XPC_toOuter;this.k.XPC_toOuter.XPC_toInner=v(this.ua,this);a=g;this.send("tp",H);this.a.l()}}catch(b){}if(a){if(!this.Ja)this.Ja=v(this.ia,this);window.setTimeout(this.Ja,100)}};J.prototype.G=function(a){if(this.a.r()==0&&!this.a.f()&&a==H){this.ya=this.k.XPC_toOuter.XPC_toInner;this.a.l()}else throw Error("Got unexpected transport message.");};
J.prototype.ua=function(a,b){if(!this.Z&&this.O.length==0)this.a.i(a,b);else{this.O.push({serviceName:a,payload:b});if(this.O.length==1)this.Cb=window.setTimeout(this.Ob,1)}};J.prototype.Xa=function(){while(this.O.length){var a=this.O.shift();this.a.i(a.serviceName,a.payload)}};J.prototype.send=function(a,b){this.Z=m;this.ya(a,b);this.Z=g};J.prototype.b=function(){J.n.b.call(this);this.ya=i;this.k=i};var K=function(a){this.a=a;this.P=this.a.c.ppu;this.Qb=this.a.c.lpu;this.aa=[]},Qb,Rb,Sb;x(K,Pb);K.prototype.ba=0;K.prototype.v=g;K.prototype.V=g;var Tb="googlexpc";K.prototype.L=function(){return Tb+"_"+this.a.name+"_msg"};K.prototype.K=function(){return Tb+"_"+this.a.name+"_ack"};K.prototype.connect=function(){if(!this.V){this.Pa();this.V=m}this.La()};K.prototype.Pa=function(){var a=this.L();this.C=this.S(a);this.wa=window.frames[a];a=this.K();this.w=this.S(a);this.fa=window.frames[a]};
K.prototype.S=function(a){var b=ib().createElement("iframe"),c=b.style;c.position="absolute";c.top="-10px";c.left="10px";c.width="1px";c.height="1px";b.id=b.name=a;b.src=this.P+"#INITIAL";document.body.appendChild(b);return b};K.prototype.Ia=function(){var a=this.a.g.frames,b=a.length;for(var c=0;c<b;c++){var d;try{if(a[c]&&a[c].name)d=a[c].name}catch(e){}if(!d)continue;var f=d.split("_");if(f.length==3&&f[0]==Tb&&f[1]=="reconnect"){this.a.name=f[2];this.Va();this.V=g;break}}};
K.prototype.Va=function(){if(this.C){this.C.parentNode.removeChild(this.C);this.C=i;this.wa=i}if(this.w){this.w.parentNode.removeChild(this.w);this.w=i;this.fa=i}};
K.prototype.La=function(){if(this.va(this.L())&&this.va(this.K())){this.nb=new Ub(this,this.a.g.frames[this.L()],v(this.sb,this));this.Ha=new Ub(this,this.a.g.frames[this.K()],v(this.rb,this));this.la()}else{if(this.a.r()==1&&!this.Sb)this.Sb=this.S(Tb+"_reconnect_"+this.a.name);else this.a.r()==0&&this.Ia();window.setTimeout(v(this.connect,this),100)}};K.prototype.va=function(a){try{var b=this.a.g.frames[a];if(!b||b.location.href.indexOf(this.Qb)!=0)return g}catch(c){return g}return m};
K.prototype.la=function(){var a=this.a.g.frames;if(a[this.K()]&&a[this.L()]){this.ob=new Vb(this.P,this.wa);this.R=new Vb(this.P,this.fa);window.setTimeout(v(function(){this.ob.send("SETUP");this.Ub=m;this.v=m},this),100)}else{if(!this.Ma)this.Ma=v(this.la,this);window.setTimeout(this.Ma,100)}};K.prototype.ka=function(){if(this.yb&&this.Rb){this.a.l();if(this.J){for(var a=0,b;a<this.J.length;a++){b=this.J[a];this.a.i(b.service,b.payload)}delete this.J}}};
K.prototype.sb=function(a){if(a=="SETUP"){if(!this.R)return;this.R.send(H);this.yb=m;this.ka()}else if(this.a.f()||this.yb){var b=a.indexOf("|"),c=a.substring(0,b),d=a.substring(b+1);b=c.indexOf(",");if(b==-1){var e=c;this.R.send("ACK:"+e);this.qa(d)}else{var e=c.substring(0,b);this.R.send("ACK:"+e);var f=c.substring(b+1).split("/");f[0]=parseInt(f[0],10);f[1]=parseInt(f[1],10);if(f[0]==1)this.za=[];this.za.push(d);if(f[0]==f[1]){this.qa(this.za.join(""));delete this.za}}}};
K.prototype.rb=function(a){if(a==H){this.v=g;this.Rb=m;this.ka()}else if(this.a.f()){if(!this.v)return;var b=parseInt(a.split(":")[1],10);if(b==this.ba){this.v=g;this.Ca()}}};K.prototype.Ca=function(){if(this.v||!this.aa.length)return;var a=this.aa.shift();++this.ba;this.ob.send(this.ba+a);this.v=m};K.prototype.qa=function(a){var b=a.indexOf(":"),c=a.substr(0,b),d=a.substring(b+1);this.a.f()?this.a.i(c,d):(this.J||(this.J=[])).push({service:c,payload:d})};K.prototype.I=3800;
K.prototype.send=function(a,b){var c=a+":"+b;if(!z||b.length<=this.I)this.aa.push("|"+c);else{var d=b.length,e=Math.ceil(d/this.I),f=0,h=1;while(f<d){this.aa.push(","+h+"/"+e+"|"+c.substr(f,this.I));h++;f+=this.I}}this.Ca()};K.prototype.b=function(){K.n.b.call(this);var a=Wb;Aa(a,this.nb);Aa(a,this.Ha);this.nb=this.Ha=i;rb(this.C);rb(this.w);this.C=this.w=i;this.wa=this.fa=i};
var Wb=[],Yb=function(){var a=g;try{for(var b=0,c=Wb.length;b<c;b++)a=a||Wb[b].receive()}catch(d){Wb[b].e.a.pb();if(!Wb.length)return}var e=wa();if(a)Qb=e;var f=e-Qb<1000?10:100;Rb=window.setTimeout(Xb,f)},Xb=v(Yb,K),Zb=function(){Qb=wa();Rb&&window.clearTimeout(Rb);Rb=window.setTimeout(Xb,10)},Vb=function(a,b){this.P=a;this.xb=b;this.pa=0};
Vb.prototype.send=function(a){this.pa=++this.pa%2;var b=this.P+"#"+this.pa+encodeURIComponent(a);try{if(A)this.xb.location.href=b;else this.xb.location.replace(b)}catch(c){}Sb=wa()};var Ub=function(a,b,c){this.e=a;this.tb=b;this.Kb=c;this.Ua=this.tb.location.href.split("#")[0]+"#INITIAL";Wb.push(this);Zb()};Ub.prototype.receive=function(){var a=this.tb.location.href;if(a!=this.Ua){this.Ua=a;var b=a.split("#")[1];if(b){b=b.substr(1);this.Kb(decodeURIComponent(b))}return m}else return g};var M=function(a,b){F.call(this);this.mb=b;this.q=[];this.Sa(a)};x(M,F);M.prototype.T=i;M.prototype.U=i;M.prototype.F=function(a){this.T=a};M.prototype.Fa=function(a){this.U=a};M.prototype.j=function(){if(this.q.length)return this.q.pop();return this.oa()};M.prototype.u=function(a){this.q.length<this.mb?this.q.push(a):this.ra(a)};M.prototype.Sa=function(a){if(a>this.mb)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.q.push(this.oa())};
M.prototype.oa=function(){return this.T?this.T():{}};M.prototype.ra=function(a){if(this.U)this.U(a);else if(u(a.dispose))a.dispose();else for(var b in a)delete a[b]};M.prototype.b=function(){M.n.b.call(this);var a=this.q;while(a.length)this.ra(a.pop());delete this.q};var N=function(a,b){this.type=a;this.target=b;this.currentTarget=this.target};x(N,F);N.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};N.prototype.D=g;N.prototype.$=m;N.prototype.stopPropagation=function(){this.D=m};N.prototype.preventDefault=function(){this.$=g};var O=function(a,b){a&&this.init(a,b)};x(O,N);O.prototype.type=i;O.prototype.target=i;O.prototype.relatedTarget=i;O.prototype.offsetX=0;O.prototype.offsetY=0;O.prototype.clientX=0;O.prototype.clientY=0;O.prototype.screenX=0;O.prototype.screenY=0;O.prototype.button=0;O.prototype.keyCode=0;O.prototype.charCode=0;O.prototype.ctrlKey=g;O.prototype.altKey=g;O.prototype.shiftKey=g;O.prototype.metaKey=g;O.prototype.h=i;
O.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;this.relatedTarget=a.relatedTarget?a.relatedTarget:this.type=="mouseover"?a.fromElement:this.type=="mouseout"?a.toElement:i;this.offsetX=typeof a.layerX=="number"?a.layerX:a.offsetX;this.offsetY=typeof a.layerY=="number"?a.layerY:a.offsetY;this.clientX=typeof a.clientX=="number"?a.clientX:a.pageX;this.clientY=typeof a.clientY=="number"?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(this.type=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.h=a;delete this.$;delete this.D};O.prototype.stopPropagation=function(){this.D=m;if(this.h.stopPropagation)this.h.stopPropagation();else this.h.cancelBubble=m};
O.prototype.preventDefault=function(){this.$=g;if(this.h.preventDefault)this.h.preventDefault();else{this.h.returnValue=g;try{this.h.keyCode=-1}catch(a){}}};O.prototype.cb=function(){return this.h};O.prototype.b=function(){O.n.b.call(this);this.h=i};var P=function(){},$b=0;P.prototype.X=i;P.prototype.listener=i;P.prototype.proxy=i;P.prototype.src=i;P.prototype.type=i;P.prototype.capture=i;P.prototype.handler=i;P.prototype.key=0;P.prototype.removed=g;P.prototype.ja=g;P.prototype.init=function(a,b,c,d,e,f){if(u(a))this.X=m;else if(a&&a.handleEvent&&u(a.handleEvent))this.X=g;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.ja=g;this.key=++$b;this.removed=g};
P.prototype.handleEvent=function(a){if(this.X)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};var cc={},Q={},dc={},ec=new M(0,600);ec.F(function(){return{o:0}});ec.Fa(function(a){a.o=0});var R=new M(0,600);R.F(function(){return[]});R.Fa(function(a){a.length=0;delete a.N;delete a.xa});var fc=new M(0,600);fc.F(function(){var a=function(b){return gc.call(a.src,a.key,b)};return a});var hc=function(){return new P},ic=new M(0,600);ic.F(hc);
var jc=function(){return new O},kc=function(){var a=i;if(z){a=new M(0,600);a.F(jc)}return a},lc=kc(),mc="on",nc={},oc=function(a,b,c,d,e){if(b)if(t(b)=="array"){for(var f=0;f<b.length;f++)oc(a,b[f],c,d,e);return i}else{var h=!!d,j=Q;b in j||(j[b]=ec.j());j=j[b];if(!(h in j)){j[h]=ec.j();j.o++}j=j[h];var k=va(a),l,n;if(j[k]){l=j[k];for(var f=0;f<l.length;f++){n=l[f];if(n.listener==c&&n.handler==e){if(n.removed)break;return l[f].key}}}else{l=j[k]=R.j();j.o++}var p=fc.j();p.src=a;n=ic.j();n.init(c,p,
a,b,h,e);var q=n.key;p.key=q;l.push(n);cc[q]=n;dc[k]||(dc[k]=R.j());dc[k].push(n);if(a.addEventListener){if(a==s||!a.Nb)a.addEventListener(b,p,h)}else a.attachEvent(pc(b),p);return q}else throw Error("Invalid event type");},qc=function(a,b,c,d,e){if(t(b)=="array"){for(var f=0;f<b.length;f++)qc(a,b[f],c,d,e);return i}var h=!!d,j=rc(a,b,h);if(!j)return g;for(var f=0;f<j.length;f++)if(j[f].listener==c&&j[f].capture==h&&j[f].handler==e)return sc(j[f].key);return g},sc=function(a){if(!cc[a])return g;var b=
cc[a];if(b.removed)return g;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==s||!c.Nb)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(pc(d),e);var h=va(c),j=Q[d][f][h];if(dc[h]){var k=dc[h];Aa(k,b);k.length==0&&delete dc[h]}b.removed=m;j.xa=m;tc(d,f,h,j);delete cc[a];return m},tc=function(a,b,c,d){if(!d.N)if(d.xa){for(var e=0,f=0;e<d.length;e++){if(d[e].removed){ic.u(d[e]);continue}if(e!=f)d[f]=d[e];f++}d.length=f;d.xa=g;if(f==0){R.u(d);delete Q[a][b][c];Q[a][b].o--;
if(Q[a][b].o==0){ec.u(Q[a][b]);delete Q[a][b];Q[a].o--}if(Q[a].o==0){ec.u(Q[a]);delete Q[a]}}}},rc=function(a,b,c){var d=Q;if(b in d){d=d[b];if(c in d){d=d[c];var e=va(a);if(d[e])return d[e]}}return i},pc=function(a){if(a in nc)return nc[a];return nc[a]=mc+a},vc=function(a,b,c,d){var e=1,f=Q;if(b in f){f=f[b];if(c in f){f=f[c];var h=va(a);if(f[h]){var j=f[h];if(j.N)j.N++;else j.N=1;try{var k=j.length;for(var l=0;l<k;l++){var n=j[l];if(n&&!n.removed)e&=uc(n,d)!==g}}finally{j.N--;tc(b,c,h,j)}}}}return Boolean(e)},
uc=function(a,b){var c=a.handleEvent(b);a.ja&&sc(a.key);return c},gc=function(a,b){if(!cc[a])return m;var c=cc[a],d=c.type,e=Q;if(!(d in e))return m;e=e[d];var f;if(z){var h=b||oa("window.event"),j=m in e;if(j){if(h.keyCode<0||h.returnValue!=undefined)return m;wc(h)}va(c.src);var k=lc.j();k.init(h,this);f=m;try{if(j){var l=R.j();for(var n=k.currentTarget;n;n=n.parentNode)l.push(n);for(var p=l.length-1;!k.D&&p>=0;p--){k.currentTarget=l[p];f&=vc(l[p],d,m,k)}for(var p=0;!k.D&&p<l.length;p++){k.currentTarget=
l[p];f&=vc(l[p],d,g,k)}}else f=uc(c,k)}finally{if(l){l.length=0;R.u(l)}k.dispose();lc.u(k)}return f}var q=new O(b,this);try{f=uc(c,q)}finally{q.dispose()}return f},wc=function(a){var b=g;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=m}if(b||a.returnValue==undefined)a.returnValue=m};var S=function(a){this.a=a;this.Pb=this.a.c.pru;this.qb=this.a.c.ifrid;A&&xc()};x(S,Pb);if(A){var yc=[],zc=0,xc=function(){zc||(zc=window.setTimeout(function(){Ac()},1000))},Ac=function(a){var b=wa(),c=a||3000;while(yc.length&&b-yc[0].timestamp>=c){var d=yc.shift().iframeElement;rb(d)}zc=window.setTimeout(Bc,1000)},Bc=function(){Ac()}}S.prototype.connect=function(){this.send("tp","SETUP")};S.prototype.G=function(a){if(a=="SETUP"){this.send("tp",H);this.a.l()}else a==H&&this.a.l()};
S.prototype.send=function(a,b){if(z){var c=document.createElement("div");c.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';var d=c.childNodes[0];d.xpcOnload=Cc}else{var d=document.createElement("iframe");A?yc.push({timestamp:wa(),iframeElement:d}):oc(d,"load",Cc)}var e=d.style;e.visibility="hidden";e.width=d.style.height="0px";e.position="absolute";var f=this.Pb;f+="#"+this.a.name;if(this.qb)f+=","+this.qb;f+="|"+a+":"+encodeURIComponent(b);d.src=f;document.body.appendChild(d)};
var Cc=function(){rb(this);this.xpcOnload=i};window.xpcRelay=function(a,b){var c=b.indexOf(":"),d=b.substring(0,c),e=b.substring(c+1);I[a].i(d,decodeURIComponent(e))};S.prototype.b=function(){S.n.b.call(this);A&&Ac(0)};var T=function(a,b){this.a=a;this.Y=b||"*"};x(T,Pb);var Dc=g,Fc=function(){if(!Dc){oc(window.postMessage?window:document,"message",Ec,g,T);Dc=m}},Ec=function(a){var b=a.cb().data,c=b.indexOf("|"),d=b.indexOf(":");if(c==-1||d==-1)return g;var e=b.substring(0,c),f=b.substring(c+1,d),h=b.substring(d+1),j=I[e];if(j){j.i(f,h);return m}for(var k in I){var l=I[k];if(l.r()==1&&!l.f()&&f=="tp"&&h=="SETUP"){l.name=e;I[e]=l;I[k]=i;l.i(f,h);return m}}return g};
T.prototype.G=function(a){switch(a){case "SETUP":if(!this.Tb){this.Tb=m;this.send("tp",H)}break;case H:this.a.l();break}};T.prototype.connect=function(){Fc();this.ma()};T.prototype.ma=function(){if(this.a.f())return;this.send("tp","SETUP");window.setTimeout(v(this.ma,this),100)};T.prototype.send=function(a,b){var c=this.a.g;if(!c)return;var d=c.postMessage?c:c.document;this.send=function(e,f){d.postMessage(this.a.name+"|"+e+":"+f,this.Y)};this.send(a,b)};
T.prototype.b=function(){T.n.b.call(this);qc(window.postMessage?window:document,"message",Ec,g,T)};var U=function(a){this.a=a;this.Ka=a.at||"";this.wb=a.rat||"";Gc();this[Hc]=this.M;this[Ic]=this.Qa};x(U,Pb);
var Jc="GRPC____NIXVBS_wrapper",Kc="GRPC____NIXVBS_get_wrapper",Hc="GRPC____NIXJS_handle_message",Ic="GRPC____NIXJS_create_channel",Lc="GRPC____NIXVBS_container",Gc=function(){if(window.nix_setup_complete)return;var a="Class "+Jc+"\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport."+Hc+
"(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport."+Ic+"(channel)\nEnd Sub\nPublic Sub "+Lc+"()\n End Sub\nEnd Class\n Function "+Kc+"(transport, auth)\nDim wrap\nSet wrap = New "+Jc+"\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet "+Kc+" = wrap\nEnd Function";try{window.execScript(a,"vbscript");window.nix_setup_complete=m}catch(b){}};U.prototype.t=g;U.prototype.m=i;U.prototype.connect=function(){this.a.r()==0?this.ha():this.ga()};
U.prototype.ha=function(){if(this.t)return;var a=this.a.s;try{a.contentWindow.opener=window[Kc](this,this.Ka);this.t=m}catch(b){}this.t||window.setTimeout(v(this.ha,this),100)};U.prototype.ga=function(){if(this.t)return;try{var a=window.opener;if(a&&Lc in a){this.m=a;var b=this.m.GetAuthToken();if(b!=this.wb)return;this.m.CreateChannel(window[Kc](this,this.Ka));this.t=m;this.a.l()}}catch(c){return}this.t||window.setTimeout(v(this.ga,this),100)};
U.prototype.Qa=function(a){this.m=a;var b=this.m.GetAuthToken();if(b!=this.wb)return;this.a.l()};U.prototype.M=function(a,b){function c(){this.a.i(a,b)}window.setTimeout(v(c,this),1)};U.prototype.send=function(a,b){this.m.SendMessage(a,b)};U.prototype.b=function(){U.n.b.call(this);this.m=i};var V=function(a){this.c=a;this.name=this.c.cn||Ob(10);this.Ea={};I[this.name]=this;oc(window,"unload",Mc)};x(V,F);V.prototype.e=i;V.prototype.da=1;V.prototype.f=function(){return this.da==2};V.prototype.g=i;V.prototype.s=i;V.prototype.Ga=function(a){this.g=a};
V.prototype.Ta=function(){if(this.e)return;if(!this.c.tp)if(u(document.postMessage)||u(window.postMessage))this.c.tp=1;else if(fb)this.c.tp=2;else if(z&&this.c.pru)this.c.tp=3;else if(z)this.c.tp=6;else if(this.c.lpu&&this.c.ppu)this.c.tp=4;switch(this.c.tp){case 1:this.e=new T(this,this.c.ph);break;case 6:this.e=new U(this);break;case 2:this.e=new J(this);break;case 3:this.e=new S(this);break;case 4:this.e=new K(this);break}if(!this.e)throw Error("CrossPageChannel: No suitable transport found!");
};V.prototype.Wa=g;V.prototype.Oa=g;V.prototype.connect=function(a){this.Mb=a;if(this.Wa){this.Oa=m;return}if(this.c.ifrid)this.s=typeof this.c.ifrid=="string"?document.getElementById(this.c.ifrid):this.c.ifrid;if(this.s){var b=this.s.contentWindow;b||(b=window.frames[this.c.ifrid]);this.Ga(b)}if(!this.g)if(window==top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");else this.Ga(window.parent);this.Ta();this.e.connect()};
V.prototype.close=function(){if(!this.f())return;this.da=3;this.e.dispose();this.e=i};V.prototype.l=function(){if(this.f())return;this.da=2;this.Mb()};V.prototype.pb=function(){this.close()};V.prototype.vb=function(a,b,c){this.Ea[a]={name:a,callback:b,jsonEncoded:!!c}};V.prototype.send=function(a,b){if(!this.f())return;if(this.g.closed){this.close();return}if(sa(b))b=Lb(b);this.e.send(a,b)};
V.prototype.i=function(a,b){if(!a||a=="tp")this.e.G(b);else if(this.f()){var c=this.Ea[a];if(c){if(c.jsonEncoded)try{b=Jb(b)}catch(d){return}c.callback(b)}}};V.prototype.r=function(){return window.parent==this.g?1:0};V.prototype.b=function(){V.n.b.call(this);this.close();this.g=i;this.s=i;delete this.Ea;I[this.name]=i};var Mc=function(){for(var a in I){var b=I[a];b&&b.dispose()}};var Nc=function(a){var b=a||document.location.protocol+"//"+document.location.host;return b+"/robots.txt"};var W=function(a,b){this.A=a.width;this.z=a.height;this.Lb=b;this.Y=this.fb(a.src,document);this.W=g;this.d=a;this.lb(this.hb(document))};W.prototype.hb=function(){var a={};a.ifrid=this.d.id;a.pu=this.d.src;a.ph=this.Y;a.cn=this.Lb;a.ppu=Nc(this.Y);a.lpu=Nc();return a};W.prototype.lb=function(a){this.a=new V(a);this.a.vb("expandable_ad",v(this.M,this));this.a.connect(function(){});window.setTimeout(v(this.jb,this),30000)};W.prototype.jb=function(){this.a&&!this.a.f()&&this.a.dispose()};
W.prototype.fb=function(a,b){var c=a.indexOf("//"),d=c>0,e=d?a.substring(0,c):b.location.protocol,f=d?a.substring(c+2):b.location.host,h=f.indexOf("/");if(h<0)h=f.indexOf("?");if(d&&h>0)f=f.substring(0,h);return e+"//"+f};W.prototype.M=function(a){var b=a.split("_"),c=b[0];if(c=="expand")this.kb(b);else c=="collapse"&&this.ib()};W.prototype.Ba=function(a){this.a.send("expandable_ad",a)};
W.prototype.kb=function(a){if(this.W)return;var b,c;for(var d in a){var e=a[d].charAt(0);if(e=="w")b=parseInt(a[d].substring(1),10);else if(e=="h")c=parseInt(a[d].substring(1),10)}var f=this.Ya(b,c);this.$a(b,c,f);this.Ba("ok_expand_w"+b+"_h"+c+"_d"+f)};W.prototype.ib=function(){if(!this.W)return;this.Na();this.Ba("ok_collapse_w"+this.A+"_h"+this.z)};
W.prototype.Na=function(){this.d.style.width=this.A+"px";this.d.style.height=this.z+"px";this.d.style.left="0";this.d.style.top="0";this.d.style.zIndex=i;this.d.parentNode.style.zIndex=i;this.W=g};
W.prototype.$a=function(a,b,c){this.d.style.position="absolute";this.d.style.width=a+"px";this.d.style.height=b+"px";this.d.style.zIndex=9999;this.d.parentNode.style.zIndex=9999;if(a>this.A&&(c==0||c==3))this.d.style.left="-"+(a-this.A)+"px";if(b>this.z&&(c==1||c==0))this.d.style.top="-"+(b-this.z)+"px";this.W=m};
W.prototype.Ya=function(a,b){var c=Ab(this.d),d=pb(window),e=a-this.A,f=b-this.z,h=c.y,j=f>h,k=d.height-(c.y+this.z),l=j||k>=h,n=c.x,p=e>n,q=d.width-(c.x+this.A),w=p||q>=n,L=0;if(l&&w)L=2;else if(l&&!w)L=3;else if(!l&&w)L=1;else if(!l&&!w)L=0;return L};xa("ExpandableAdSlot",W);var Oc=0;function Pc(a){return a!=i?'"'+a+'"':'""'}function ha(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function X(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function Y(a){var b=window,c=ba[a]||ca[a]||i,d=b[a];X(c,d)}function Z(a,b){b!=i&&X(a,ha(b))}function $(a){var b=window,c=ba[a]||ca[a]||i,d=b[a];Z(c,d)}function Qc(a,b){var c=window,d=ba[a]||ca[a]||i,e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];X(d,e)}
function Rc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){X("u_h",b.height);X("u_w",b.width);X("u_ah",b.availHeight);X("u_aw",b.availWidth);X("u_cd",b.colorDepth)}X("u_tz",d);X("u_his",history.length);X("u_java",c);navigator.plugins&&X("u_nplug",navigator.plugins.length);navigator.mimeTypes&&X("u_nmime",navigator.mimeTypes.length)}
function Sc(a){if(!a.google_enable_first_party_cookie)return;if(o==i)o=new da;if(a._GA_googleCookieHelper==i)a._GA_googleCookieHelper=new r;if(!a._google_cookie_fetched){a._google_cookie_fetched=m;a._GA_googleCookieHelper.ab(Tc(a.google_ad_client))}}function Tc(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function Uc(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}
function Vc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}function Wc(){var a=z&&B("6")&&!B("8"),b=fb&&B("1.8.1"),c=A&&B("525");if(Xa&&(a||b||c))return m;else if(Wa&&(c||b))return m;else if(Ya&&b)return m;return g}function Xc(a,b){var c=a.google_allow_expandable_ads;if(c!=i&&c==g||!b.body||a.google_ad_output!="html"||Yc(a,b)||Zc(a)||$c(a.google_ad_format)||!Wc())return g;return m}
function ad(){var a=Math.random();if(a<0.03)return 30143001;else if(a<0.06)return 30143002;return 0}function bd(a){a.google_allow_expandable_ads=g;a.google_expandable_iframe=g}var cd=Math.random()<0.0010;function dd(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function ed(a,b,c,d,e,f){var h="google_ads_frame"+b,j="<iframe allowtransparency=true frameborder=0 height="+e+" hspace=0 id="+h+' marginheight=0 marginwidth=0 name=google_ads_frame scrolling=no src="'+fd(c)+'" style="left:0;position:absolute;top:0" vspace=0 width='+d+"></iframe>",k=f.getElementById(a);if(k)k.innerHTML=j;else f.write('<ins id="'+a+'" style="width:'+d+"px;height:"+e+'px;position:relative;margin:0;padding:0;display:block;visibility:visible;border:none">'+j+"</ins>");return f.getElementById(h)}
function gd(a,b,c,d){var e=Vc(a),f=a.google_container_id||d||"google_ad_div"+e;c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var h="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+h+' language="JavaScript1.1" src='+Pc(fd(c))+"></"+h+">");else if(a.google_ad_output=="html")if(b.body&&(a.google_expandable_iframe||Oc==30143002)){var j=parseInt(a.google_ad_width,10),k=parseInt(a.google_ad_height,10),l=Ob(10),
n=c+(c.indexOf("?")==-1?"?":"&")+"w="+j+"&h="+k+"&xpc="+l+"&p="+escape(b.location.protocol+"//"+b.location.host),p=ed(f,e,n,j,k,b);a["google_expandable_ad_slot"+e]=new W(p,l)}else{var q='<iframe name="google_ads_frame" width='+Pc(a.google_ad_width)+" height="+Pc(a.google_ad_height)+" frameborder="+Pc(a.google_ad_frameborder)+" src="+Pc(fd(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?hd(a.google_container_id,b,
q):b.write(q)}else a.google_ad_output=="textlink"&&b.write("<"+h+' language="JavaScript1.1" src='+Pc(fd(c))+"></"+h+">");if(cd){var w=id(a)+"/pagead/gen_204?id=ifjs2&token="+a.google_correlator+"&output="+ha(a.google_ad_output)+"&url="+ha(a.google_page_url);dd(a,w)}}function jd(a){for(var b in ba)a[b]=i;for(var b in ca){if(b=="google_correlator")continue;a[b]=i}a.google_container_id=i}
function Zc(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function $c(a){return a&&a.indexOf("_sdo")!=-1}
function kd(a){var b=i,c=window,d=document,e=aa,f=c.google_ad_format,h=id(c),j;if(c.google_cpa_choice!=b){c.google_ad_url=h+"/cpa/ads?";j=escape(Tc(c.google_ad_client));c.google_ad_region="_google_cpa_region_";Y("google_cpa_choice");if(typeof d.characterSet!="undefined")Z("oe",d.characterSet);else typeof d.charset!="undefined"&&Z("oe",d.charset)}else if($c(f)){c.google_ad_url=h+"/pagead/sdo?";j=escape(Uc(c.google_ad_client))}else{c.google_ad_url=h+"/pagead/ads?";j=escape(Tc(c.google_ad_client))}c.google_ad_url+=
"client="+j;Y("google_ad_host");Y("google_ad_host_tier_id");var k=c.google_num_slots_by_client,l=c.google_num_slots_by_channel,n=c.google_prev_ad_formats_by_region,p=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var q=c.google_ad_region==b?"":c.google_ad_region;if($c(f)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>4)return g}else if(Zc(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?
c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return g}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){n[q]=b;p[q]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=e%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return g}else if(c.google_num_ad_slots>6&&q=="")return g}X("dt",aa);Y("google_language");c.google_country?Y("google_country"):Y("google_gl");Y("google_region");
$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");var w=c.google_ad_client;if(k[w])k[w]+=1;else{k[w]=1;k.length+=1}if(n[q])if(!$c(f)){Z("prev_fmts",n[q].toLowerCase());k.length>1&&X("slot",k[w])}p[q]&&Z("prev_slotnames",p[q].toLowerCase());if(f&&!c.google_ad_slot){Z("format",f.toLowerCase());$c(f)||(n[q]=n[q]?n[q]+","+f:f)}if(c.google_ad_slot)p[q]=p[q]?
p[q]+","+c.google_ad_slot:c.google_ad_slot;Y("google_max_num_ads");X("output",c.google_ad_output);Y("google_adtest");Y("google_ad_callback");Y("google_ad_slot");$("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&X("dblk",1);if(c.google_ad_channel){$("google_ad_channel");var L="",ac=c.google_ad_channel.split(ld);for(var bb=0;bb<ac.length;bb++){var cb=ac[bb];if(l[cb])L+=cb+"+";else l[cb]=1}Z("pv_ch",L)}if(c.google_ad_host_channel){$("google_ad_host_channel");var sd=
md(c.google_ad_host_channel,c.google_viewed_host_channels);Z("pv_h_ch",sd)}c.google_enable_first_party_cookie&&Z("cookie",c._GA_googleCookieHelper.gb());$("google_page_url");Qc("google_color_bg",e);Qc("google_color_text",e);Qc("google_color_link",e);Qc("google_color_url",e);Qc("google_color_border",e);Qc("google_color_line",e);c.google_reuse_colors?X("reuse_colors",1):X("reuse_colors",0);Y("google_kw_type");$("google_kw");$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");
Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");Y("google_ad_region");if(!Xc(c,d))bd(c);else if(c.google_expandable_iframe===g)bd(c);else if(j in{"ca-pub-2944451727872625":1,"ca-pub-9483266128490610":1,"ca-pub-1955924717845427":1,"ca-pub-6664249124335298":1})c.google_expandable_iframe=m;else if(!(c.google_expandable_iframe==m)){Oc=ad();X("eid",Oc);bd(c)}var bc=c.google_allow_expandable_ads;if(bc!=i)bc?X("ea","1"):
X("ea","0");Y("google_feedback");$("google_referrer_url");$("google_page_location");X("frm",c.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");$("google_only_ads_with_video");$("google_disable_video_autoplay");
if(a){Z("ff",Bb(a));var db=zb(a),eb=pb();if(db&&eb){Z("biw",eb.width);Z("bih",eb.height);Z("adx",db.x);Z("ady",db.y)}}Db();X("ga_vid",c.gaGlobal.vid);X("ga_sid",c.gaGlobal.sid);X("ga_hid",c.gaGlobal.hid);X("ga_fc",c.gaGlobal.from_cookie);$("google_analytics_uacct");Y("google_ad_override");Y("google_flash_version");Rc(c);cd&&X("gen_204","ifjs2");return m}
function md(a,b){var c=a.split("|"),d=-1,e=[];for(var f=0;f<c.length;f++){var h=c[f].split(ld);b[f]||(b[f]={});var j="";for(var k=0;k<h.length;k++){var l=h[k];if(b[f][l])j+="+"+l;else b[f][l]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var n="";if(d>-1){for(var f=0;f<d;f++)n+=e[f]+"|";n+=e[d]}return n}
function nd(){var a=window,b=document;Sc(a);var c;if(Math.random()<0.01){var d="google_temp_span";if(!mb(d)){b.write("<span id="+d+"></span>");c=mb(d)}}var e=kd(c);c&&rb(c);if(!e)return;gd(a,b,a.google_ad_url);jd(a)}function fd(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c}function od(){nd();return m}
function Yc(a,b){if(a.top.location==b.location)return g;var c=b.documentElement;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return g}return m}
function pd(a){var b=window,c=i,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if($c(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;qd(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=aa;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=ja();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function rd(a){if(a in td)return td[a];return td[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var td={};function ka(){return rd("msie")&&!window.opera}
function ud(a){var b={},c=a.split("?"),d=c[c.length-1].split("&");for(var e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(h){}}return b}function vd(){var a=window,b=ud(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function wd(a,b){for(var c in b)a["google_"+c]=b[c]}
function xd(a,b){if(!b)return a.location;return a.referrer}function yd(a,b){if(!b&&a.google_referrer_url==i)return"0";else if(b&&a.google_referrer_url==i)return"1";else if(!b&&a.google_referrer_url!=i)return"2";else if(b&&a.google_referrer_url!=i)return"3";return"4"}function zd(a,b,c,d){a.page_url=xd(c,d);a.page_location=i}function Ad(a,b,c,d){a.page_url=b.google_page_url;a.page_location=xd(c,d)||"EMPTY"}
function Bd(a,b){var c={},d=Yc(a,b);c.iframing=yd(a,d);!!a.google_page_url?Ad(c,a,b,d):zd(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:i;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Cd(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=i;b.page_url=c;b.page_location=a.location;b.last_modified_time=i;b.referrer_url=c;return b}
function qd(a,b){var c;c=a.google_page_url==i&&Dd[b.domain]?Cd(b):Bd(a,b);wd(a,c)}function hd(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var Dd={};Dd["ad.yieldmanager.com"]=m;var ld=/[+, ]/;window.google_render_ad=nd;var Ed={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};function Fd(a){var b=a.google_page_location||a.google_page_url;if(!b)return g;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=g;if(e.length>=3)f=e[e.length-3]in Ed;if(e.length>=2)f=f||e[e.length-2]in Ed;return f}
function Gd(a,b,c){if(a.google_new_domain_checked==0){var d=Math.random();if(d<c){var e="http://googleads.g.doubleclick.net/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return m}}return g}function id(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!Fd(a)&&a.google_new_domain_enabled==1)return b;return c};function Hd(a,b){var c="script",d=Gd(a,b,ia("1",0.01));d&&ka()?b.write("<"+c+' src="http://pagead2.googlesyndication.com/pagead/render_ads.js"></'+c+">"):b.write("<"+c+">window.google_render_ad();</"+c+">")}vd();pd(od);Hd(window,document);
})()
